apiVersion: v1
kind: Service
metadata:
  namespace: devopselite
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
