apiVersion: v1
kind: Namespace
metadata:
  name: devopselite
  labels:
    name: devopselite

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devopselite
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:15.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "kubenews"
            - name: POSTGRES_USER
              value: "kubenews"
            - name: POSTGRES_PASSWORD
              value: "Pg#123"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devopselite
  name: web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: wagnercastro/kube-news
          ports:
            - containerPort: 8080
          env:
            - name: DB_DATABASE
              value: "kubenews"
            - name: DB_USERNAME
              value: "kubenews"
            - name: DB_PASSWORD
              value: "Pg#123"
            - name: DB_HOST
              value: "postgre"

---

apiVersion: v1
kind: Service
metadata:
  namespace: devopselite
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  namespace: devopselite
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
